name: CI

on:
  push:
  pull_request:

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0
      with:
        persist-credentials: false
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        architecture: 'x64'
    - name: Restore
      run: |
        python -m pip install -r requirements.txt
    - name: Build
      env:
        PYTHONUTF8: 1
      run: |
        ./build.ps1
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: ./dist
  integration-test:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python: ["3.10"]
        experimental: [false]
    continue-on-error: ${{ matrix.experimental }}
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
      with:
        persist-credentials: false
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
        architecture: 'x64'
    - name: Restore
      run: |
        python -m pip install -r requirements.txt
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: dist
        path: ./dist
    - name: Test
      env:
        PYTHONUTF8: 1
      run: |
        ./build.ps1 test
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: test-cov-${{ matrix.os }}
        path: ./htmlcov
  deploy-testcov:
    needs: integration-test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
      with:
        persist-credentials: false
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: test-cov-ubuntu-latest
        path: ./htmlcov
    - name: Remove gitignore
      run: |
        rm ./htmlcov/.gitignore
    - name: Deploy GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        token: ${{ secrets.PA_TOKEN }}
        branch: gh-pages
        folder: ./htmlcov