name: Release

on:
  release:
    types: [published]

defaults:
  run:
    shell: pwsh

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
      with:
        persist-credentials: false
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        architecture: 'x64'
    - name: Install build tools
      run: |
        python -m pip install --upgrade build twine
    - name: Build package
      run: |
        python -m build
    - name: Upload
      env:
        TWINE_USERNAME: '__token__'
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        python -m twine upload --repository pypi dist/*
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: ./dist